config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :hearts, only: :create
  get 'about' => "pages#about"

  root 'pages#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :post
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :hearts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
  def create
    @heart = Heart.new(heart_params)


      if @heart.save
       redirect_to @heart.post, notice: 'Hearted that post!'
      else
      redirect_to root_url, notice: "Had an issue creating that heart"
      end
    end

    def heart_params
      params.require(:heart).permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :kind, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crumblr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
    <body>
      <div class="container">

        <div class="card ">

          <div class ="card-text">
              <ul class="nav nav-pills float-right">
                <li class="nav-item">
                  <%= link_to "Home", root_url, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "About", about_url, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "Manage Posts", posts_url, class: "nav-link" %>
                </li>
              </ul>
          </div>
          <div class ='card-header'>
            <h1>
              <%= link_to "crumblr", "/"%>
            </h1>
            <small class = 'float-right text-muted'>//home baked goodness</small>
          </div>
        </div>
        <div class = "row ">
          <div class = "col-md-6 offset-md-3">
            <%= yield %>
          </div>
        </div>


      </div>
    </body>


</html>

app/views/pages/about.html.erb
<h1 class = "display-4">About</h1>

<p>This app was built in Tal Safrans <%= link_to "Ruby on Rails class on Skillshare","http://skillshare.talsafran.com"  %></p>

app/views/pages/welcome.html.erb
<% @posts.each do |post|%>
<%= render 'posts/post', post: post%>
<br> <br> <br> 

<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class = 'form-group'>
    <%= form.label :kind %> <br>
    <%= form.select :kind, ['text', 'image'],{} , class: 'custom-select custom-select-sm' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save new post", class:"btn btn-primary" %>
  </div>
  
<% end %>

app/views/posts/_post.html.erb
<p>
  <h2>
    <%= link_to post.title, post %>
    <div class = "float-right">
      <%=form_for(Heart.new) do |f| %>
        <%= f.hidden_field :post_id, value: post.id %>
        <%= f.submit " ❤️ ", class:"btn btn-link" %>
      <% end %>
    </div>
  </h2>
</p>

<p>
  <% if post.kind == 'image' %>
    <%= image_tag post.content, style: 'width: 100%' %>
  <% else %>
    <%= simple_format post.content %>
  <% end %>
</p>

<p class = "text-info">
  <small>
   Posted on <%= post.created_at.to_formatted_s(:long) %>
   </small>

   <small class= "float-right">
     <%= post.hearts.count %> Hearts
   </small>
</p>

app/views/posts/edit.html.erb
<h1 class = "display-4">Edit Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class = "display-4">My Posts</h1>


  <table class = "table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= truncate(post.content, length: 50) %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
  <p class = 'alert alert-info'><%= notice %></p>
<% end %>
<%= render 'post', post:@post%>